media: media

content:
  - name: posts
    label: Blog posts
    type: collection
    path: src/content/post
    format: yaml-frontmatter
    fields:
      - name: title
        type: string
      - name: description
        type: string
      - name: dateFormatted
        type: string
      - name: layout
        type: string
        hidden: true
        readonly: true
      - name: body
        type: rich-text

  - name: projects
    label: Projects
    type: file
    path: src/collections/projects.json
    format: json
    list:
      collapsible:
        summary: "{name}"
    fields:
      - name: name
        type: string
      - name: description
        type: text
      - name: image
        type: image
      - name: url
        type: string

  - name: experiences
    label: Experiences
    type: file
    path: src/collections/experiences.json
    format: json
    list:
      collapsible:
        summary: "{role}"
    fields:
      - name: dates
        type: string
      - name: role
        type: string
      - name: company
        type: string
      - name: description
        type: text
      - name: logo
        type: image

  - name: skills
    label: Skills
    type: file
    path: src/collections/skills.json
    format: json
    fields:
      - name: categories
        label: Categories
        type: object
        list: true
        fields:
          - name: id
            label: ID
            type: string
          - name: label
            label: Label
            type: string
          - name: color
            label: Color
            type: string
          - name: children
            label: Children
            type: object
            list: true
            fields:
              - name: id
                label: ID
                type: string
              - name: label
                label: Label
                type: string
              - name: color
                label: Color
                type: string
              - name: children
                label: Skills
                type: object
                list: true
                fields:
                  - name: id
                    label: ID
                    type: string
                  - name: label
                    label: Label
                    type: string
                  - name: svg
                    label: SVG Image URL
                    type: string

